### ISSUE TITLE
Running the examples

### ISSUE THREAD

**Issue by vkeryvin** [nennigb/amc2moodle#37]
In these COVID times your repository attracted me.

I am running the three examples provided  (QCM, QCM_wo-tikz and numerical).
For the latter it works fine.
For the two first ones I a experiencing the following issue 

> Running Python conversion...
Traceback (most recent call last):
  File "/Users/vkeryvin/opt/anaconda3/bin/amc2moodle", line 117, in <module>
    run()
  File "/Users/vkeryvin/opt/anaconda3/bin/amc2moodle", line 108, in run
    magic_flag=magic_flag)
  File "/Users/vkeryvin/opt/anaconda3/lib/python3.7/site-packages/amc2moodle/amc2moodle/amc2moodle_class.py", line 149, in __init__
    self.runBuilding()
  File "/Users/vkeryvin/opt/anaconda3/lib/python3.7/site-packages/amc2moodle/amc2moodle/amc2moodle_class.py", line 271, in runBuilding
    deb=self.deb)
  File "/Users/vkeryvin/opt/anaconda3/lib/python3.7/site-packages/amc2moodle/amc2moodle/convert.py", line 1006, in to_moodle
    quiz.toMoodle(os.path.join(pathout, fileout))
  File "/Users/vkeryvin/opt/anaconda3/lib/python3.7/site-packages/amc2moodle/amc2moodle/convert.py", line 781, in toMoodle
    self._graphics()
  File "/Users/vkeryvin/opt/anaconda3/lib/python3.7/site-packages/amc2moodle/amc2moodle/convert.py", line 890, in _graphics
    img_name = Ii.attrib['candidates'].split(',')[-1]   #get the last candidates
  File "src/lxml/etree.pyx", line 2479, in lxml.etree._Attrib.__getitem__
KeyError: 'candidates'

I'm using OSX 10.15.5
Thank you for your repo and hope you can help me.

**Comment by nennigb** [comment]
Hi,

The problem seems related to the figures processing (the 'numerical' test file has no figure).
It seems that the object `Ii` has no attribute `candidates`. I can reproduce this problem if the full filename in the `includegraphics` latex command is wrong.

Could you check that the image files are present in your installation ? 
```
/Users/vkeryvin/opt/anaconda3/lib/python3.7/site-packages/amc2moodle/amc2moodle/test
```
Does LateXML mention "Conversion complete: No obvious problems." (look just before the error message you have posted)
How have you run the test ? in which folder ?
Have you install `imagemagick` ?

**Comment by vkeryvin** [comment]
thank you for you answer. It was indeed the absence of the Figures folder that made it wrong. It works fine now. Thanks.

**Comment by nennigb** [comment]
Cool. 

I will add a more explicit message for this error.
