### ISSUE TITLE
Does amc2moodle work with pyparsing 3?

### ISSUE THREAD

**Issue by pablo-angulo** [nennigb/amc2moodle#64]
After upgrading to pyparsing 3.0.7, I get the following error when running amc2moodle 

```
Traceback (most recent call last):
  File "/usr/local/bin/amc2moodle", line 22, in <module>
    from amc2moodle.amc2moodle import amc2moodle_class as a2m
  File "/home/USER/.local/lib/python3.8/site-packages/amc2moodle/amc2moodle/amc2moodle_class.py", line 22, in <module>
    from ..amc2moodle import convert
  File "/home/USER/.local/lib/python3.8/site-packages/amc2moodle/amc2moodle/convert.py", line 29, in <module>
    from ..utils.calculatedParser import *
  File "/home/USER/.local/lib/python3.8/site-packages/amc2moodle/utils/calculatedParser.py", line 11, in <module>
    from pyparsing import Word, alphas, nums, alphas, alphanums, Char, oneOf,\
ImportError: cannot import name '_flatten' from 'pyparsing' (/usr/local/lib/python3.8/dist-packages/pyparsing/__init__.py)
```

Regards

**Comment by nennigb** [comment]
Thanks for reporting. I can reproduce your problem.
I will have a look.

**Comment by nennigb** [comment]
For version 3, pyparsing team makes a major refactor. The `_flatten` function has been moved in the `util` submodule.
Changing the line 11 of `amc2moodle/utils/calculatedParser.py` into
```
from pyparsing import Word, alphas, nums, alphas, alphanums, Char, oneOf,\
                      Suppress, Combine, Regex, Group, ZeroOrMore, Literal,\
                      Forward, Optional, ParseResults
from pyparsing.util import _flatten
```
should work. I will do the modification asap.

**Comment by pablo-angulo** [comment]
quick as hell, as usual!
